### ISSUE TITLE
exchange button

### ISSUE THREAD

**Issue by pisqua187** [PJanisio/Xiaomi_Yi_autoexec#11]
sorry for wrong section but i can do a pull request hahah!     hi! i broken flat ribbon cable on top of camera and now shutter button doens't work. is it possibile to made a script where i can use just a mode button for do everthing? like: long press=change mode  ,  short press start record /take pic

**Comment by PJanisio** [comment]
Well, maybe there is an option, but i would rather recommend to change flat ribbon :)
