### ISSUE TITLE
HDMI resolution/fps change

### ISSUE THREAD

**Issue by damjanZG** [PJanisio/Xiaomi_Yi_autoexec#12]
Hi,

Is it possible to change HDMI out video resolution/FPS. This would be great if it is possible. By default output is 1080i. 1080p/60fps would be great.

**Comment by PJanisio** [comment]
I do not see possibility in the firmware.

**Comment by damjanZG** [comment]
Hi,

In this file https://github.com/PJanisio/Xiaomi_Yi_autoexec/blob/master/!!commands_extracted/1.2.13/strings.txt i have found this:

------ HDMI 2D Video capabilities ------
HDMI_VO_480I
HDMI_VO_480P
HDMI_VO_720P
HDMI_VO_1080I
HDMI_VO_1080P
HDMI_VO_576I
HDMI_VO_576P
HDMI_VO_720P50
HDMI_VO_1080I50
HDMI_VO_1080P50
HDMI_VO_1080P24
HDMI_VO_1080P25
HDMI_VO_1080P30
HDMI_VO_720P24
HDMI_VO_720P25
HDMI_VO_720P30
------ HDMI extended Video capabilities ------
HDMI_VO_4KX2KP30
HDMI_VO_4KX2KP25
HDMI_VO_4KX2KP24
HDMI_VO_4KX2KP24_SMPTE
------ HDMI 3D Video capabilities ------
pxdI
sy4ys
There are no HDMI extended video formats.

So there is really no possibility to change it. :(

**Comment by PJanisio** [comment]
Yup.
