### ISSUE TITLE
File is empty in "telnet_open/enable_info_display.script

### ISSUE THREAD

**Issue by kcINual** [PJanisio/Xiaomi_Yi_autoexec#3]
Just to report missing content in 
"Xiaomi_Yi_autoexec/telnet_open/enable_info_display.script"
https://github.com/PJanisio/Xiaomi_Yi_autoexec/blob/master/telnet_open/enable_info_display.script

**Comment by PJanisio** [comment]
Hi,

File has to be empty. It is just filename causing that telnet will be available. 

So simple :-)

**Comment by kcINual** [comment]
Thanks PJanisio! :)
