### ISSUE TITLE
Please document differences in adress lines

### ISSUE THREAD

**Issue by filimonic** [PJanisio/Xiaomi_Yi_autoexec#4]
Here is an example from bitrates:

```
id	Width	Height	Fps	Default	address
168	848	480	119.88	4140	0xC05C28D2
169	848	480	119.88	4120	0xC05C28E2
170	848	480	119.88	4100	0xC05C28F2
```

I can not understand the differences between those lines except adresses. Please let me to choose which one I need

**Comment by PJanisio** [comment]
This is almost raw export from firmware, so there will be some duplicated resolutions which differs by frames per second /default bitrate and address of course.

General rule is that 1st position works. If no - than i suggest to put into autoexec all three and change their bitrates.

If you find it uncomfortable you can also check funneld`s script - > https://github.com/funneld/XiaomiYi/blob/master/autoexec.ash/1.2.13-fw/set_all_bitrate_resolution_script.ash

It is better organised i suppose :)

IMHO - better way to change bitrate is to flash custom firmware with predefined bitrate value for all existing resolutions.
