### ISSUE TITLE
Documentation of the RAW files

### ISSUE THREAD

**Issue by supertobi** [PJanisio/Xiaomi_Yi_autoexec#8]
Do you have a documentation of the RAW file format?

**Comment by serg3y** [comment]
From memory it is uncompressed uint16 RGGB Bayer pattern, 4000 x 3000 (hero 3 plus black), no header.
R G R G ..
G B G B ..
.   .   .  .  ..
I have a MatLab function to read it but that's probably of little help to you..
You will probably find a bunch of bad pixels you might want to identify and remove before converting to normal RGB.

**Comment by jgrocha** [comment]
I was able to read Yi raw format in Ubuntu with [darktable](https://www.darktable.org/).

**Comment by supertobi** [comment]
If darktable can read it, everything is fine. :)
